name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & push the Docker image
      env:
        CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
      run: |
        docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
    - name: report image by action
      with:
        CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
#        CF_ENRICHERS: "jira"
        # Specify cluster app-proxy
        CF_HOST: "https://saffi.pipeline-team.cf-cd.com/app-proxy"
        CF_VERBOSE: "1"
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
      uses: codefresh-io/csdp-report-image@0.0.24


