name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/quick-start:0.0.2
        run: |
          docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
          echo "Image should be accessible to your local machine (after docker login) by:"
          echo "docker pull $CF_IMAGE"
          docker pull $CF_IMAGE
          echo "On the next step, the report image would use the integration to pull information on the reported image, and using the specified enrichers."
          CF_JIRA_MESSAGE="Example for inserting branch name: $(echo ${GITHUB_REF##*/}) like CR-11027-fix-report "
          echo "CF_JIRA_MESSAGE=$CF_JIRA_MESSAGE" >> $GITHUB_ENV
      

      - name: report image
        with:
          # Runtime to use for the enrichment.
          CF_RUNTIME_NAME: 'codefresh-hosted'

          # API key for authentication to Codefresh. !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_API_KEY: ${{ secrets.API_KEY }}

          # Image reported and enriched in Codefresh. Pass the [account-name]/[image-name]:[tag] built in your CI.
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/quick-start:0.0.2

          # Container registry integration where the image is stored.
          CF_CONTAINER_REGISTRY_INTEGRATION: 'default-dockerhub'

          # Git branch with the commit  Pull Request data to add to the image. Pass the branch from the event payload used to trigger your action.
#           CF_GIT_BRANCH: '[name-of-your-git-branch]'

          # GitHub authentication token. !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_GITHUB_TOKEN:  ${{ secrets.CF_GITHUB_TOKEN }}

          # Issue tracking integration to use to enrich the image.
          CF_JIRA_INTEGRATION: 'default-jira'

          # Jira project prefix  identifying the ticket number to use.
          CF_JIRA_PROJECT_PREFIX: 'CR'

          # Search for issue IDs matching this string to associate with your image.
          CF_JIRA_MESSAGE: "CR-1234"
          


        uses: codefresh-io/codefresh-report-image@latest
